<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>1.4.1</Version>
    <FileVersion>1.4.1.0</FileVersion>
    <Product>PassKeeper</Product>
    <Company>PassKeeper</Company>
    <Copyright>© 2026 PassKeeper</Copyright>
    <Description>PassKeeper — офлайн менеджер паролей</Description>
    <NeutralLanguage>ru-RU</NeutralLanguage>
    <SatelliteResourceLanguages>en;ru</SatelliteResourceLanguages>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>
</Project>
