namespace PassKeeper.Localization;

/// <summary>UI strings: key → (Russian, English).</summary>
internal static class Strings
{
    public static readonly Dictionary<string, (string Ru, string En)> Table = new()
    {
        // ---- common
        ["Common.Ok"] = ("ОК", "OK"),
        ["Common.Cancel"] = ("Отмена", "Cancel"),
        ["Common.Close"] = ("Закрыть", "Close"),
        ["Common.Continue"] = ("Продолжить", "Continue"),
        ["Common.Back"] = ("Назад", "Back"),
        ["Common.Save"] = ("Сохранить", "Save"),
        ["Common.Edit"] = ("Изменить", "Edit"),
        ["Common.Delete"] = ("Удалить", "Delete"),
        ["Common.Copy"] = ("Копировать", "Copy"),
        ["Common.Cut"] = ("Вырезать", "Cut"),
        ["Common.Paste"] = ("Вставить", "Paste"),
        ["Common.SelectAll"] = ("Выделить всё", "Select all"),
        ["Common.ShowHide"] = ("Показать / скрыть", "Show / hide"),
        ["Common.Password"] = ("Пароль", "Password"),
        ["Common.PasswordRepeat"] = ("Повторите пароль", "Repeat password"),
        ["Common.ErrorFormat"] = ("Ошибка: {0}", "Error: {0}"),
        ["Common.OfflineNote"] = ("Зашифровано и хранится только на этом компьютере", "Encrypted and stored only on this computer"),
        ["Plural.Entries"] = ("запись|записи|записей", "entry|entries"),

        // ---- setup
        ["Setup.Title"] = ("Добро пожаловать в PassKeeper", "Welcome to PassKeeper"),
        ["Setup.Subtitle"] = ("Создайте локальный профиль. Пароли хранятся только на этом компьютере и шифруются по современным стандартам (AES‑256‑GCM, Argon2id). Подключение к интернету не требуется.",
            "Create a local profile. Passwords stay on this computer and are encrypted with modern standards (AES‑256‑GCM, Argon2id). No internet connection is required."),
        ["Setup.UserName"] = ("Имя пользователя", "User name"),
        ["Setup.UserNamePlaceholder"] = ("Как к вам обращаться", "How should we call you"),
        ["Setup.Master"] = ("Мастер‑пароль", "Master password"),
        ["Setup.MasterPlaceholder"] = ("Не менее 8 символов", "At least 8 characters"),
        ["Setup.Confirm"] = ("Повторите мастер‑пароль", "Repeat master password"),
        ["Setup.ConfirmPlaceholder"] = ("Ещё раз", "Once again"),
        ["Setup.Autostart"] = ("Запускать PassKeeper при входе в Windows", "Start PassKeeper when I sign in to Windows"),
        ["Setup.Warning"] = ("Мастер‑пароль невозможно восстановить или сбросить. Запомните его — без него доступ к паролям будет потерян.",
            "The master password cannot be recovered or reset. Remember it — without it your passwords are lost."),
        ["Setup.Create"] = ("Создать профиль", "Create profile"),
        ["Setup.ErrName"] = ("Введите имя пользователя", "Enter a user name"),
        ["Setup.ErrShort"] = ("Пароль должен содержать не менее {0} символов", "The password must be at least {0} characters long"),
        ["Setup.ErrExists"] = ("Пользователь с таким именем уже есть — войдите в него или выберите другое имя", "A user with this name already exists: sign in or choose another name"),
        ["Setup.SignIn"] = ("У меня уже есть профиль — войти", "I already have a profile: sign in"),
        ["Login.Title"] = ("Вход в PassKeeper", "Sign in to PassKeeper"),
        ["Login.Subtitle"] = ("Введите имя пользователя и мастер‑пароль. Пользователи хранятся только на этом компьютере.", "Enter the user name and master password. Users are stored on this computer only."),
        ["Login.Users"] = ("Пользователи на этом компьютере", "Users on this computer"),
        ["Login.UserNamePlaceholder"] = ("Имя пользователя", "User name"),
        ["Login.Button"] = ("Войти", "Sign in"),
        ["Login.PinNote"] = ("После входа нужно будет придумать новый PIN‑код.", "After signing in you will set a new PIN."),
        ["Login.Create"] = ("Создать нового пользователя", "Create a new user"),
        ["Login.UnknownUser"] = ("Пользователь с таким именем не найден", "No user with this name"),
        ["Profile.Section"] = ("Профиль", "Profile"),
        ["Profile.Hint"] = ("Выход удаляет PIN‑код; войти снова можно по имени пользователя и мастер‑паролю. Удаление пользователя стирает его хранилище, PIN и резервные копии.",
            "Signing out deletes the PIN; sign in again with the user name and master password. Deleting the user erases the vault, PIN and backups."),
        ["Profile.MenuTip"] = ("Профиль: блокировка, выход, удаление", "Profile: lock, sign out, delete"),
        ["Profile.Lock"] = ("Заблокировать (Ctrl+L)", "Lock (Ctrl+L)"),
        ["Profile.SignOut"] = ("Выйти из профиля", "Sign out"),
        ["Profile.SignOutTitle"] = ("Выйти из профиля?", "Sign out?"),
        ["Profile.SignOutText"] = ("PIN‑код пользователя «{0}» будет удалён. Пароли останутся на компьютере; чтобы войти снова, понадобятся имя пользователя и мастер‑пароль, затем новый PIN.",
            "The PIN of “{0}” will be deleted. The passwords stay on this computer; signing in again takes the user name and master password, then a new PIN."),
        ["Profile.Delete"] = ("Удалить пользователя…", "Delete user…"),
        ["Profile.DeleteTitle"] = ("Удалить пользователя «{0}»?", "Delete the user “{0}”?"),
        ["Profile.DeleteText"] = ("Хранилище паролей, PIN‑код и резервные копии этого пользователя будут стёрты безвозвратно. Если пароли ещё нужны, сначала сделайте экспорт. Для подтверждения введите мастер‑пароль.",
            "The password vault, PIN and backups of this user will be erased permanently. If you still need the passwords, export them first. Enter the master password to confirm."),
        ["Profile.DeleteButton"] = ("Удалить навсегда", "Delete permanently"),
        ["Profile.Deleted"] = ("Пользователь «{0}» удалён", "The user “{0}” was deleted"),
        ["Setup.ErrMismatch"] = ("Пароли не совпадают", "Passwords do not match"),

        // ---- PIN
        ["Pin.Title"] = ("Придумайте PIN‑код", "Choose a PIN"),
        ["Pin.Subtitle"] = ("PIN используется для быстрого входа при запуске и после {0} бездействия. После 5 неверных попыток потребуется мастер‑пароль.",
            "The PIN unlocks PassKeeper at start-up and after {0} of inactivity. After 5 wrong attempts the master password is required."),
        ["Pin.New"] = ("PIN‑код", "PIN"),
        ["Pin.Repeat"] = ("Повторите PIN‑код", "Repeat PIN"),
        ["Pin.Hint"] = ("От 4 до 12 цифр. Рекомендуем 6 и более.", "4 to 12 digits. 6 or more recommended."),
        ["Pin.Save"] = ("Сохранить PIN", "Save PIN"),
        ["Pin.ErrLength"] = ("PIN должен состоять из {0}–{1} цифр", "The PIN must have {0}–{1} digits"),
        ["Pin.ErrMismatch"] = ("PIN‑коды не совпадают", "PINs do not match"),
        ["Pin.ErrSimple"] = ("Слишком простой PIN (одинаковые цифры или последовательность)", "PIN is too simple (repeated digits or a sequence)"),
        ["Pin.Changed"] = ("PIN‑код изменён", "PIN changed"),

        // ---- unlock
        ["Unlock.Greeting"] = ("Здравствуйте, {0}!", "Hello, {0}!"),
        ["Unlock.PromptPin"] = ("Введите PIN‑код, чтобы разблокировать хранилище", "Enter your PIN to unlock the vault"),
        ["Unlock.PromptMaster"] = ("Введите мастер‑пароль, чтобы разблокировать хранилище", "Enter your master password to unlock the vault"),
        ["Unlock.PinPlaceholder"] = ("PIN‑код", "PIN"),
        ["Unlock.MasterPlaceholder"] = ("Мастер‑пароль", "Master password"),
        ["Unlock.Button"] = ("Разблокировать", "Unlock"),
        ["Unlock.UseMaster"] = ("Войти с мастер‑паролем", "Use master password"),
        ["Unlock.UsePin"] = ("Войти с PIN‑кодом", "Use PIN"),
        ["Unlock.WrongPin"] = ("Неверный PIN‑код. Осталось попыток: {0}", "Wrong PIN. Attempts left: {0}"),
        ["Unlock.WrongMaster"] = ("Неверный мастер‑пароль", "Wrong master password"),
        ["Unlock.LockedOut"] = ("Слишком много неверных попыток. PIN‑код сброшен — войдите с мастер‑паролем и задайте новый PIN.",
            "Too many wrong attempts. The PIN was reset — sign in with the master password and set a new PIN."),
        ["Unlock.PinReset"] = ("PIN‑код недоступен. Войдите с мастер‑паролем.", "The PIN is not available. Sign in with the master password."),
        ["Unlock.Corrupted"] = ("Не удалось открыть хранилище: {0}", "Cannot open the vault: {0}"),

        // ---- quick unlock / picker / suggestions
        ["Quick.Title"] = ("Разблокируйте для автозаполнения", "Unlock to autofill"),
        ["Quick.TitleFor"] = ("Разблокируйте для автоввода: {0}", "Unlock to auto-type into {0}"),
        ["Picker.Target"] = ("Автоввод: {0}", "Auto-type: {0}"),
        ["Picker.Search"] = ("Поиск записи", "Search entries"),
        ["Picker.Hint"] = ("Enter — ввести · ↑↓ — выбор · Esc — отмена", "Enter — type · ↑↓ — select · Esc — cancel"),
        ["Suggest.For"] = ("Для: {0}", "For: {0}"),
        ["Suggest.Footer"] = ("{0} — автоввод в активное окно", "{0} — auto-type into the active window"),
        ["Suggest.PasswordOnly"] = ("только пароль", "password only"),
        ["Suggest.FillOtp"] = ("вставить код 2FA", "fill 2FA code"),
        ["Suggest.FillPin"] = ("вставить PIN‑код", "fill PIN"),
        ["Suggest.FillKey"] = ("вставить ключ / токен", "fill key / token"),
        ["Suggest.Unlock"] = ("PassKeeper заблокирован", "PassKeeper is locked"),
        ["Suggest.UnlockHint"] = ("Нажмите, чтобы разблокировать и заполнить", "Click to unlock and fill"),
        ["Suggest.Choose"] = ("Выбрать запись…", "Choose an entry…"),
        ["Suggest.ChooseHint"] = ("Для этого сайта записей нет: подойдёт любая, например учётка VPN — сайт запомнится для неё", "No entries for this site: any entry will do, e.g. a VPN account; the site is remembered for it"),
        ["Picker.Remember"] = ("Запомнить выбор для {0}", "Remember the choice for {0}"),
        ["Suggest.Create"] = ("Создать запись для «{0}»", "Create an entry for “{0}”"),
        ["Suggest.CreateHint"] = ("Клиент и поля уже определены; логин и пароль можно взять из записи сайта", "The client and its fields are recognised; the login and password can be taken from a site entry"),

        // ---- vault
        ["Nav.All"] = ("Все записи", "All entries"),
        ["Nav.Favorites"] = ("Избранное", "Favorites"),
        ["Nav.Folders"] = ("Папки", "Folders"),
        ["Nav.Sections"] = ("Разделы", "Sections"),
        ["Category.Web"] = ("Сайты", "Websites"),
        ["Category.Remote"] = ("VPN и удалённый доступ", "VPN and remote access"),
        ["Category.App"] = ("Программы", "Programs"),
        ["Category.Other"] = ("Другое", "Other"),
        ["Nav.Trash"] = ("Корзина", "Trash"),
        ["Vault.Generator"] = ("Генератор паролей", "Password generator"),
        ["Vault.Import"] = ("Импорт", "Import"),
        ["Vault.Export"] = ("Экспорт", "Export"),
        ["Vault.Settings"] = ("Настройки", "Settings"),
        ["Vault.LocalProfile"] = ("Локальный профиль", "Local profile"),
        ["Vault.LockTip"] = ("Заблокировать (Ctrl+L)", "Lock (Ctrl+L)"),
        ["Vault.SearchPlaceholder"] = ("Поиск (Ctrl+F)", "Search (Ctrl+F)"),
        ["Vault.AddTip"] = ("Новая запись (Ctrl+N)", "New entry (Ctrl+N)"),
        ["Vault.AddShort"] = ("Добавить", "Add"),
        ["Vault.CopyLogin"] = ("Копировать логин", "Copy login"),
        ["Vault.CopyPassword"] = ("Копировать пароль", "Copy password"),
        ["Vault.OpenSite"] = ("Открыть сайт", "Open website"),
        ["Vault.Favorite"] = ("В избранное", "Add to favorites"),
        ["Vault.Unfavorite"] = ("Убрать из избранного", "Remove from favorites"),
        ["Vault.Duplicate"] = ("Дублировать", "Duplicate"),
        ["Vault.CopyOf"] = ("{0} (копия)", "{0} (copy)"),
        ["Vault.UseForSite"] = ("Использовать для сайта…", "Use for a website…"),
        ["Vault.UseForClient"] = ("Использовать для VPN или программы…", "Use for a VPN client or program…"),
        ["Vault.CopiedFromNote"] = ("Логин и пароль взяты из записи «{0}».", "Login and password taken from “{0}”."),
        ["Vault.Help"] = ("Справка", "Help"),
        ["Vault.FindClients"] = ("Найти клиенты на компьютере", "Find clients on this computer"),
        ["Vault.EmptySection"] = ("В разделе пока нет записей", "No entries in this section yet"),
        ["Vault.EmptyRemoteHint"] = ("PassKeeper сам найдёт установленные и запущенные VPN‑клиенты. Или нажмите Ctrl+Alt+A в окне входа клиента — запись создастся для него.",
            "PassKeeper finds installed and running VPN clients itself. Or press Ctrl+Alt+A in a client's sign-in window to create an entry for it."),
        ["Vault.EmptyAppHint"] = ("Добавьте программу из списка или нажмите Ctrl+Alt+A в её окне входа.", "Pick a program from the list or press Ctrl+Alt+A in its sign-in window."),
        ["Vault.SyncTitle"] = ("Обновить пароль и в других записях?", "Update the password in other entries too?"),
        ["Vault.SyncText"] = ("Старый пароль ещё используется в записях {0}. Если это та же учётная запись (например, доменная для сайта и VPN), обновите их сразу.",
            "The old password is still used by {0}. If it is the same account (for example a domain account for a site and a VPN), update them now."),
        ["Vault.SyncButton"] = ("Обновить", "Update"),
        ["Vault.Synced"] = ("Пароль обновлён ещё в: {0}", "Password also updated in {0}"),
        ["Vault.Restore"] = ("Восстановить", "Restore"),
        ["Vault.Restored"] = ("Запись восстановлена", "Entry restored"),
        ["Vault.MovedToTrash"] = ("Запись перемещена в корзину", "Entry moved to trash"),
        ["Vault.DeleteForever"] = ("Удалить навсегда", "Delete forever"),
        ["Vault.DeleteForeverTitle"] = ("Удалить запись навсегда?", "Delete the entry forever?"),
        ["Vault.DeleteForeverText"] = ("Запись «{0}» будет удалена без возможности восстановления.", "“{0}” will be deleted permanently."),
        ["Vault.DeletedForever"] = ("Запись удалена", "Entry deleted"),
        ["Vault.EmptyTrash"] = ("Очистить корзину", "Empty trash"),
        ["Vault.EmptyTrashTitle"] = ("Очистить корзину?", "Empty the trash?"),
        ["Vault.EmptyTrashText"] = ("Все записи в корзине будут удалены без возможности восстановления.", "All entries in the trash will be deleted permanently."),
        ["Vault.TrashEmptied"] = ("Корзина очищена ({0})", "Trash emptied ({0})"),
        ["Vault.NoEntries"] = ("Здесь пока пусто", "Nothing here yet"),
        ["Vault.NoEntriesHint"] = ("Добавьте первую запись или импортируйте пароли из браузера и других менеджеров.", "Add your first entry or import passwords from your browser and other managers."),
        ["Vault.EmptyFolder"] = ("Нет записей", "No entries"),
        ["Vault.NothingFound"] = ("Ничего не найдено", "Nothing found"),
        ["Vault.NothingFoundHint"] = ("Попробуйте изменить запрос", "Try a different search"),
        ["Vault.TrashEmpty"] = ("Корзина пуста", "Trash is empty"),
        ["Vault.TrashEmptyHint"] = ("Удалённые записи хранятся здесь, пока вы не очистите корзину.", "Deleted entries stay here until you empty the trash."),
        ["Sort.Name"] = ("По названию", "By name"),
        ["Sort.Modified"] = ("По изменению", "Recently changed"),
        ["Sort.Used"] = ("По использованию", "Recently used"),

        // ---- details
        ["Details.EmptyTitle"] = ("Выберите запись", "Select an entry"),
        ["Details.EmptyHint"] = ("или создайте новую — Ctrl+N", "or create a new one — Ctrl+N"),
        ["Details.StatTotal"] = ("паролей", "passwords"),
        ["Details.StatWeak"] = ("слабых", "weak"),
        ["Details.StatReused"] = ("повторяются", "reused"),
        ["Details.AutoTypeTip"] = ("Сайты заполняются сами, когда курсор попадает в пустое поле входа. В программах и VPN‑клиентах нажмите Ctrl+Alt+A или включите в записи автовход.",
            "Sites are filled in by themselves when the cursor enters an empty sign-in field. In programs and VPN clients press Ctrl+Alt+A or turn on automatic sign-in in the entry."),
        ["Details.CustomFields"] = ("Дополнительные поля", "Custom fields"),
        ["Details.AutoType"] = ("Автоввод", "Auto-type"),
        ["Details.AutoTypeButton"] = ("Автоввод", "Auto-type"),
        ["Details.AutoTypeButtonTip"] = ("Ввести логин и пароль в окно клиента этой записи или в предыдущее окно", "Type the login and password into this entry's client window or the previous window"),
        ["Details.History"] = ("История паролей ({0})", "Password history ({0})"),
        ["Details.Meta"] = ("Создано {0} · Изменено {1}", "Created {0} · Modified {1}"),
        ["Details.Used"] = ("Использовано {0}", "Used {0}"),
        ["Details.InTrash"] = ("В корзине", "In trash"),
        ["Details.Open"] = ("Открыть", "Open"),
        ["Details.Sec"] = ("с", "s"),

        // ---- fields
        ["Field.Title"] = ("Название", "Title"),
        ["Field.Login"] = ("Логин", "Login"),
        ["Field.Password"] = ("Пароль", "Password"),
        ["Field.Website"] = ("Сайт", "Website"),
        ["Field.Email"] = ("Эл. почта", "Email"),
        ["Field.Phone"] = ("Телефон", "Phone"),
        ["Field.Key"] = ("Ключ / токен", "Key / token"),
        ["Field.Totp"] = ("Код 2FA (TOTP)", "2FA code (TOTP)"),
        ["Field.Folder"] = ("Папка", "Folder"),
        ["Field.Notes"] = ("Заметки", "Notes"),
        ["Field.Windows"] = ("Окна приложения", "Application windows"),
        ["Field.ExtraUrls"] = ("Другие адреса этого сайта", "Other addresses of this site"),
        ["Field.Sequence"] = ("Последовательность автоввода", "Auto-type sequence"),

        // ---- editor
        ["Editor.NewTitle"] = ("Новая запись", "New entry"),
        ["Editor.EditTitle"] = ("Редактирование", "Edit entry"),
        ["Editor.TitlePlaceholder"] = ("Например, Почта или 1С", "e.g. Mail or CRM"),
        ["Editor.LoginPlaceholder"] = ("Логин, e‑mail или телефон", "Login, e-mail or phone"),
        ["Editor.KeyPlaceholder"] = ("API‑ключ, лицензия, токен", "API key, licence, token"),
        ["Editor.TotpPlaceholder"] = ("otpauth://… или секрет Base32", "otpauth://… or Base32 secret"),
        ["Editor.FolderPlaceholder"] = ("Без папки (вложенность через /)", "No folder (use / for sub-folders)"),
        ["Editor.Generate"] = ("Сгенерировать пароль", "Generate password"),
        ["Editor.Favorite"] = ("Добавить в избранное", "Add to favorites"),
        ["Editor.AddField"] = ("+ Добавить поле", "+ Add field"),
        ["Editor.NoFields"] = ("Например: ПИН карты, кодовое слово, номер договора.", "e.g. card PIN, secret word, contract number."),
        ["Editor.FieldName"] = ("Название поля", "Field name"),
        ["Editor.FieldValue"] = ("Значение", "Value"),
        ["Editor.FieldProtected"] = ("Скрывать значение", "Hide the value"),
        ["Editor.FieldDefault"] = ("Поле", "Field"),
        ["Editor.AutoTypeSection"] = ("Автоввод: окна и последовательность", "Auto-type: windows and sequence"),
        ["Editor.PhonePlaceholder"] = ("+7 900 000-00-00", "+1 555 000 0000"),
        ["Editor.Section"] = ("Раздел", "Section"),
        ["Editor.Client"] = ("Клиент или программа", "Client or program"),
        ["Editor.ChooseClient"] = ("Выбрать…", "Choose…"),
        ["Editor.ClientKnown"] = ("Распознаётся по окнам: {0}", "Recognised by windows: {0}"),
        ["Editor.ClientCustom"] = ("Своя программа", "Custom program"),
        ["Editor.ClientNone"] = ("Клиент не выбран", "No client chosen"),
        ["Editor.ClientNoneHint"] = ("Нажмите «Выбрать» — запущенные и установленные клиенты найдутся сами", "Press Choose: running and installed clients are found automatically"),
        ["Editor.TakeFromEntry"] = ("Взять логин и пароль из другой записи…", "Take login and password from another entry…"),
        ["Editor.TakenFrom"] = ("Логин и пароль взяты из «{0}»", "Login and password taken from “{0}”"),
        ["Editor.Pin"] = ("PIN‑код токена", "Token PIN"),
        ["Editor.PinPlaceholder"] = ("Если клиент запрашивает PIN", "If the client asks for a PIN"),
        ["Editor.PinRequired"] = ("Клиент запрашивает PIN — введите его", "The client asks for a PIN: enter it"),
        ["Editor.Server"] = ("Адрес сервера", "Server address"),
        ["Editor.AutoLogin"] = ("Входить автоматически", "Sign in automatically"),
        ["Editor.AutoLoginHint"] = ("Когда появится окно входа клиента, PassKeeper заполнит поля и нажмёт Enter. Не больше 2 попыток за 10 минут — неверный пароль не заблокирует учётную запись.",
            "When the client's sign-in window appears, PassKeeper fills the fields and presses Enter. At most 2 attempts in 10 minutes, so a wrong password cannot lock the account."),
        ["Editor.FillAfterSave"] = ("После сохранения выполнить вход в это окно", "Sign in to this window after saving"),
        ["Editor.DetectTitle"] = ("Для «{0}» ещё нет записи", "There is no entry for “{0}” yet"),
        ["Editor.DetectFields"] = ("В окне найдены поля: {0}. Заполните их здесь или возьмите логин и пароль из записи сайта.",
            "Fields found in the window: {0}. Fill them in here or take the login and password from a site entry."),
        ["Editor.DetectNoFields"] = ("Поля окна не распознаны: PassKeeper введёт логин, Tab и пароль туда, где стоит курсор.",
            "The window's fields are not recognised: PassKeeper types the login, Tab and password where the cursor is."),
        ["Editor.FieldLogin"] = ("логин", "login"),
        ["Editor.FieldPassword"] = ("пароль", "password"),
        ["Editor.FieldPin"] = ("PIN‑код", "PIN"),
        ["Editor.FieldOtp"] = ("одноразовый код", "one-time code"),
        ["Editor.SummaryFields"] = ("Заполнение по полям окна", "Fills the window's fields"),
        ["Editor.SummarySequence"] = ("Последовательность {0}", "Sequence {0}"),
        ["Editor.SummaryWindows"] = ("окон: {0}", "windows: {0}"),
        ["Editor.HowItWorks"] = ("Как это работает. Для сайтов достаточно адреса, для программ — выбранного клиента: PassKeeper сам находит в окне поля логина, пароля, PIN и кода и заполняет каждое. Последовательность нужна, только если поля не распознаются (терминалы, нестандартные окна): тогда PassKeeper печатает её туда, где стоит курсор, как если бы вы набирали сами.",
            "How it works. A site needs only its address, a program only the chosen client: PassKeeper finds the login, password, PIN and code fields in the window and fills each of them. A sequence is needed only when fields are not recognised (terminals, custom windows): PassKeeper then types it where the cursor is, as if you typed it."),
        ["Editor.WindowsHelp"] = ("По одной строке: имя процесса (csc_ui.exe) или заголовок окна; * — любые символы (*Cisco*). Кнопка «Выбрать» заполнит строки сама.",
            "One per line: a process name (csc_ui.exe) or a window title; * matches any text (*Cisco*). The Choose button fills them in for you."),
        ["Editor.ExtraUrlsHelp"] = ("Подсказка появляется, когда адрес страницы совпадает с адресом записи. Если тот же аккаунт открывается и на других адресах (mail.example.com, id.example.com), добавьте их сюда — по одному на строку.",
            "The suggestion appears when the page address matches the entry's address. If the same account also opens on other addresses (mail.example.com, id.example.com), add them here, one per line."),
        ["Editor.SequencePlaceholder"] = ("Пусто — заполнение по полям окна", "Empty: fill the window's fields"),
        ["Editor.SequenceHelp"] = ("Текст в фигурных скобках заменяется данными записи или нажатием клавиши, остальное печатается как есть. Нажмите на подстановку, чтобы вставить её; правый клик — копировать.",
            "Text in braces is replaced by the entry's data or a key press; everything else is typed as is. Click a placeholder to insert it; right-click to copy."),
        ["Editor.Examples"] = ("Готовые варианты", "Ready-made sequences"),
        ["Editor.ExLoginPassword"] = ("Логин → Tab → пароль → Enter", "Login → Tab → password → Enter"),
        ["Editor.ExPassword"] = ("Только пароль и Enter", "Password and Enter"),
        ["Editor.ExPin"] = ("PIN токена и Enter", "Token PIN and Enter"),
        ["Editor.ExTerminal"] = ("Терминал SSH: логин, пауза, пароль", "SSH terminal: login, pause, password"),
        ["Editor.ExTwoFactor"] = ("Пароль, затем код 2FA", "Password, then 2FA code"),
        ["Editor.OpenHelp"] = ("Подробнее в справке", "More in Help"),
        ["Editor.Ph.USERNAME"] = ("Логин записи (если пуст — e-mail)", "The entry's login (e-mail if empty)"),
        ["Editor.Ph.PASSWORD"] = ("Пароль", "Password"),
        ["Editor.Ph.PIN"] = ("PIN‑код токена (если не задан — пароль)", "Token PIN (the password if not set)"),
        ["Editor.Ph.TAB"] = ("Клавиша Tab — переход к следующему полю", "Tab key: next field"),
        ["Editor.Ph.ENTER"] = ("Клавиша Enter — отправить форму", "Enter key: submit the form"),
        ["Editor.Ph.DELAY"] = ("Пауза в миллисекундах (500 = полсекунды)", "Pause in milliseconds (500 = half a second)"),
        ["Editor.Ph.TOTP"] = ("Текущий код 2FA из поля TOTP", "Current 2FA code from the TOTP field"),
        ["Editor.Ph.EMAIL"] = ("E-mail записи", "The entry's e-mail"),
        ["Editor.Ph.PHONE"] = ("Телефон записи", "The entry's phone"),
        ["Editor.Ph.KEY"] = ("Ключ / токен записи", "The entry's key / token"),
        ["Editor.Ph.CLEARFIELD"] = ("Очистить поле перед вводом", "Clear the field before typing"),
        ["Editor.Ph.S"] = ("Значение дополнительного поля по его имени", "Value of a custom field by its name"),
        ["Editor.ErrAutoLoginClient"] = ("Для автовхода выберите клиент или программу — иначе PassKeeper не узнает её окно.", "Choose the client or program for automatic sign-in, otherwise PassKeeper cannot recognise its window."),
        ["Editor.WindowsPlaceholder"] = ("*1С:Предприятие*\nmstsc.exe", "*Remote Desktop*\nputty.exe"),
        ["Editor.ExtraUrlsPlaceholder"] = ("Другие адреса этого же аккаунта, по одному на строку", "Other addresses of the same account, one per line"),
        ["Editor.ErrTitle"] = ("Укажите название записи", "Enter a title"),
        ["Editor.ErrSequence"] = ("Ошибка в последовательности автоввода: {0}", "Auto-type sequence error: {0}"),
        ["Editor.ErrTotp"] = ("Неверный формат 2FA: нужен секрет Base32 или ссылка otpauth://", "Invalid 2FA value: use a Base32 secret or an otpauth:// link"),
        ["Editor.Created"] = ("Запись создана", "Entry created"),
        ["Editor.Saved"] = ("Изменения сохранены", "Changes saved"),
        ["Editor.DiscardTitle"] = ("Отменить изменения?", "Discard changes?"),
        ["Editor.DiscardText"] = ("Несохранённые изменения будут потеряны.", "Unsaved changes will be lost."),
        ["Editor.Discard"] = ("Не сохранять", "Discard"),

        // ---- generator & strength
        ["Generator.Title"] = ("Генератор паролей", "Password generator"),
        ["Generator.Length"] = ("Длина", "Length"),
        ["Generator.ExcludeAmbiguous"] = ("Исключить похожие символы (I, l, 1, O, 0)", "Exclude look-alike characters (I, l, 1, O, 0)"),
        ["Generator.Regenerate"] = ("Сгенерировать заново", "Regenerate"),
        ["Generator.Use"] = ("Использовать", "Use password"),
        ["Generator.CopyAndClose"] = ("Копировать и закрыть", "Copy and close"),
        ["Strength.Empty"] = ("Надёжность пароля", "Password strength"),
        ["Strength.Format"] = ("{0} · ≈{1} бит", "{0} · ≈{1} bits"),
        ["Strength.0"] = ("Очень слабый", "Very weak"),
        ["Strength.1"] = ("Слабый", "Weak"),
        ["Strength.2"] = ("Средний", "Fair"),
        ["Strength.3"] = ("Надёжный", "Strong"),
        ["Strength.4"] = ("Очень надёжный", "Very strong"),

        // ---- toasts
        ["Toast.PasswordCopied"] = ("Пароль скопирован", "Password copied"),
        ["Toast.LoginCopied"] = ("Логин скопирован", "Login copied"),
        ["Toast.TotpCopied"] = ("Код 2FA скопирован", "2FA code copied"),
        ["Toast.Copied"] = ("{0}: скопировано", "{0} copied"),
        ["Toast.CopiedSecret"] = ("{0}: скопировано", "{0} copied"),
        ["Toast.WillClear"] = ("очистится через {0} с", "clears in {0} s"),
        ["Toast.ClipboardBusy"] = ("Буфер обмена занят другой программой", "The clipboard is busy"),

        // ---- settings
        ["Settings.Title"] = ("Настройки", "Settings"),
        ["Settings.General"] = ("Общие", "General"),
        ["Settings.Language"] = ("Язык интерфейса", "Language"),
        ["Settings.Theme"] = ("Оформление", "Appearance"),
        ["Settings.ThemeDark"] = ("Тёмное", "Dark"),
        ["Settings.ThemeLight"] = ("Светлое", "Light"),
        ["Settings.ThemeSystem"] = ("Как в Windows", "System"),
        ["Settings.Autostart"] = ("Запускать вместе с Windows", "Start with Windows"),
        ["Settings.AutostartHint"] = ("Работает без прав администратора; PassKeeper запускается свёрнутым в трей", "No administrator rights needed; PassKeeper starts minimized to the tray"),
        ["Settings.AutostartMachine"] = ("Автозапуск включён администратором для всех пользователей", "Autostart is enabled by the administrator for all users"),
        ["Settings.Tray"] = ("Сворачивать в трей при закрытии", "Minimize to tray on close"),
        ["Settings.TrayHint"] = ("Автозаполнение и горячие клавиши работают, пока PassKeeper запущен", "Autofill and hotkeys work while PassKeeper is running"),
        ["Settings.Security"] = ("Безопасность", "Security"),
        ["Settings.AutoLock"] = ("Автоблокировка при бездействии", "Auto-lock after inactivity"),
        ["Settings.AutoLockHint"] = ("Если за это время не было действий с клавиатурой и мышью, потребуется PIN‑код. Точность — до секунды, рекомендуется 8 ч.",
            "With no keyboard or mouse activity for this long, the PIN is required. Set to the second; 8 h is recommended."),
        ["Duration.Hours"] = ("часы", "hours"),
        ["Duration.Minutes"] = ("минуты", "minutes"),
        ["Duration.Seconds"] = ("секунды", "seconds"),
        ["Duration.Minimum"] = ("Минимум — {0}: будет применено это значение", "The minimum is {0}: this value will be used"),
        ["Settings.Clipboard"] = ("Очищать буфер обмена", "Clear clipboard"),
        ["Settings.ClipboardHint"] = ("Скопированные пароли не попадают в журнал буфера Windows", "Copied passwords are excluded from Windows clipboard history"),
        ["Settings.LockOnWindowsLock"] = ("Блокировать при блокировке Windows (Win+L)", "Lock when Windows is locked (Win+L)"),
        ["Settings.ChangeMaster"] = ("Сменить мастер‑пароль", "Change master password"),
        ["Settings.ChangePin"] = ("Сменить PIN‑код", "Change PIN"),
        ["Settings.Autofill"] = ("Автозаполнение", "Autofill"),
        ["Settings.Hotkey"] = ("Горячая клавиша автоввода", "Auto-type hotkey"),
        ["Settings.HotkeyHint"] = ("Работает во всех браузерах и программах", "Works in every browser and application"),
        ["Settings.HotkeyPress"] = ("Нажмите сочетание…", "Press a shortcut…"),
        ["Settings.HotkeyTaken"] = ("Сочетание занято другой программой", "The shortcut is used by another application"),
        ["Settings.AutoFillWeb"] = ("Автоматически заполнять сайты", "Fill in sites automatically"),
        ["Settings.AutoFillWebHint"] = ("Когда на странице входа курсор стоит в пустом поле и для сайта есть одна запись, логин и пароль подставляются сами. Если записей несколько — рядом с полем появится список для выбора.",
            "When the cursor is in an empty field on a sign-in page and one entry matches the site, the login and password are filled in by themselves. With several entries a list to choose from appears next to the field."),
        ["Settings.AutoLogin"] = ("Автовход в программы", "Automatic sign-in to programs"),
        ["Settings.AutoLoginHint"] = ("Для записей с включённым автовходом: при появлении окна входа поля заполняются, Enter нажимается сам. Если хранилище заблокировано, PassKeeper спросит PIN.",
            "For entries with automatic sign-in: when the sign-in window appears the fields are filled and Enter is pressed. If the vault is locked, PassKeeper asks for the PIN."),
        ["Settings.Suggestions"] = ("Подсказки у полей входа", "Suggestions at login fields"),
        ["Settings.SuggestionsHint"] = ("При фокусе на поле логина или пароля в браузере или программе PassKeeper предложит подходящую запись",
            "When a login or password field is focused in a browser or app, PassKeeper offers the matching entry"),
        ["Settings.Submit"] = ("Нажимать Enter после заполнения", "Press Enter after filling"),
        ["Settings.Compatible"] = ("Совместимый режим ввода", "Compatibility typing mode"),
        ["Settings.CompatibleHint"] = ("Для RDP, терминалов и старых программ, которые не принимают Unicode‑ввод", "For RDP, terminals and legacy apps that ignore Unicode input"),
        ["Settings.KeyDelay"] = ("Задержка между нажатиями", "Delay between keystrokes"),
        ["Settings.Data"] = ("Данные", "Data"),
        ["Settings.DataFolder"] = ("Папка хранилища", "Vault folder"),
        ["Settings.OpenFolder"] = ("Открыть папку", "Open folder"),
        ["Settings.Backup"] = ("Сохранить резервную копию…", "Save a backup…"),
        ["Settings.BackupFilter"] = ("Хранилище PassKeeper", "PassKeeper vault"),
        ["Settings.BackupDone"] = ("Резервная копия сохранена", "Backup saved"),
        ["Settings.About"] = ("О программе", "About"),
        ["Settings.AboutText"] = ("Менеджер паролей для изолированных сетей: не использует интернет, телеметрию и облака. Шифрование AES‑256‑GCM, ключ из мастер‑пароля — Argon2id (64 МБ, 3 прохода).",
            "Password manager for isolated networks: no internet, telemetry or cloud. AES‑256‑GCM encryption, key derived from the master password with Argon2id (64 MB, 3 passes)."),
        ["Settings.ModeUser"] = ("Установлено для текущего пользователя", "Installed for the current user"),
        ["Settings.ModeMachine"] = ("Установлено для всех пользователей", "Installed for all users"),
        ["Settings.ModePortable"] = ("Портативный режим", "Portable mode"),
        ["Settings.Uninstall"] = ("Удалить PassKeeper…", "Uninstall PassKeeper…"),
        ["Settings.ModeStandalone"] = ("Запущено без установки", "Running without installation"),
        ["Settings.Minutes"] = ("{0} мин", "{0} min"),
        ["Settings.Hours"] = ("{0} ч", "{0} h"),
        ["Settings.Seconds"] = ("{0} с", "{0} s"),
        ["Settings.Milliseconds"] = ("{0} мс", "{0} ms"),
        ["Settings.Never"] = ("Никогда", "Never"),
        ["Settings.Recommended"] = ("(рекомендуется)", "(recommended)"),
        ["ChangeMaster.Title"] = ("Смена мастер‑пароля", "Change master password"),
        ["ChangeMaster.Text"] = ("Хранилище будет перешифровано новым ключом. PIN‑код продолжит работать.", "The vault key will be re-wrapped with the new password. Your PIN keeps working."),
        ["ChangeMaster.Current"] = ("Текущий мастер‑пароль", "Current master password"),
        ["ChangeMaster.New"] = ("Новый мастер‑пароль", "New master password"),
        ["ChangeMaster.Confirm"] = ("Повторите новый мастер‑пароль", "Repeat new master password"),
        ["ChangeMaster.Button"] = ("Сменить пароль", "Change password"),
        ["ChangeMaster.Done"] = ("Мастер‑пароль изменён", "Master password changed"),

        // ---- import
        ["Import.Title"] = ("Импорт паролей", "Import passwords"),
        ["Import.Subtitle"] = ("Перенесите пароли из браузеров, других менеджеров паролей и файлов. Дубликаты будут найдены автоматически.",
            "Bring in passwords from browsers, other password managers and files. Duplicates are detected automatically."),
        ["Import.Browsers"] = ("Браузеры на этом компьютере", "Browsers on this computer"),
        ["Import.Refresh"] = ("Обновить", "Refresh"),
        ["Import.NoBrowsers"] = ("Браузеры с сохранёнными паролями не найдены.", "No browsers with saved passwords were found."),
        ["Import.FromBrowsers"] = ("Импортировать из выбранных", "Import from selected"),
        ["Import.FromFileTitle"] = ("Файл экспорта", "Export file"),
        ["Import.Formats"] = ("CSV любых браузеров (Chrome, Edge, Яндекс, Opera, Firefox, Safari), KeePass / KeePassXC (KDBX, XML, CSV), Bitwarden (JSON, CSV), 1Password (1PUX, CSV), LastPass, Dashlane, NordPass, Proton Pass, RoboForm, Keeper, Kaspersky Password Manager (TXT), PassKeeper (PKX, JSON). Формат определяется автоматически.",
            "CSV from any browser (Chrome, Edge, Yandex, Opera, Firefox, Safari), KeePass / KeePassXC (KDBX, XML, CSV), Bitwarden (JSON, CSV), 1Password (1PUX, CSV), LastPass, Dashlane, NordPass, Proton Pass, RoboForm, Keeper, Kaspersky Password Manager (TXT), PassKeeper (PKX, JSON). The format is detected automatically."),
        ["Import.ChooseFile"] = ("Выбрать файл…", "Choose file…"),
        ["Import.ChromeTip"] = ("Chrome 127+ шифрует новые пароли так, что другие программы не могут их прочитать. Если часть паролей не импортировалась, экспортируйте их в браузере (Настройки → Менеджер паролей → Экспорт) и выберите полученный CSV.",
            "Chrome 127+ encrypts new passwords so that other apps cannot read them. If some passwords were skipped, export them in the browser (Settings → Password Manager → Export) and choose the CSV file."),
        ["Import.Other"] = ("Другие источники", "Other sources"),
        ["Import.WindowsCredentials"] = ("Диспетчер учётных данных Windows", "Windows Credential Manager"),
        ["Import.WindowsCredentialsHint"] = ("Общие учётные данные текущего пользователя", "Generic credentials of the current user"),
        ["Import.Read"] = ("Прочитать", "Read"),
        ["Import.Reading"] = ("Чтение и расшифровка данных…", "Reading and decrypting…"),
        ["Import.Supported"] = ("Поддерживаемые файлы", "Supported files"),
        ["Import.AllFiles"] = ("Все файлы", "All files"),
        ["Import.KdbxPasswordTitle"] = ("База KeePass", "KeePass database"),
        ["Import.PkxPasswordTitle"] = ("Резервная копия PassKeeper", "PassKeeper backup"),
        ["Import.FilePasswordText"] = ("Файл «{0}» зашифрован. Введите пароль.", "“{0}” is encrypted. Enter its password."),
        ["Import.KeyFile"] = ("Файл‑ключ…", "Key file…"),
        ["Import.NoKeyFile"] = ("Файл‑ключ не выбран (необязательно)", "No key file (optional)"),
        ["Import.WrongPassword"] = ("Неверный пароль или файл‑ключ.", "Wrong password or key file."),
        ["Import.ErrorTitle"] = ("Не удалось импортировать", "Import failed"),
        ["Import.ErrorText"] = ("Не удалось прочитать файл: {0}", "Cannot read the file: {0}"),
        ["Import.FirefoxPrimaryTitle"] = ("Основной пароль Firefox", "Firefox primary password"),
        ["Import.FirefoxPrimaryText"] = ("В профиле «{0}» установлен основной пароль. Введите его, чтобы расшифровать сохранённые пароли.", "Profile “{0}” is protected by a primary password. Enter it to decrypt the saved logins."),
        ["Import.Found"] = ("Найдено: {0}", "Found: {0}"),
        ["Import.CountNew"] = ("Новых: {0}", "New: {0}"),
        ["Import.CountConflict"] = ("Другой пароль: {0}", "Different password: {0}"),
        ["Import.CountDuplicate"] = ("Уже есть: {0}", "Already saved: {0}"),
        ["Import.StatusNew"] = ("Новая", "New"),
        ["Import.StatusConflict"] = ("Другой пароль", "Changed"),
        ["Import.StatusDuplicate"] = ("Уже есть", "Exists"),
        ["Import.SelectAll"] = ("Выбрать все", "Select all"),
        ["Import.Filter"] = ("Фильтр", "Filter"),
        ["Import.TargetFolder"] = ("Поместить в папку", "Put into folder"),
        ["Import.NoFolder"] = ("Сохранить исходные папки", "Keep original folders"),
        ["Import.Conflicts"] = ("Если пароль отличается", "If the password differs"),
        ["Import.ConflictUpdate"] = ("Обновить пароль (старый — в историю)", "Update password (keep old in history)"),
        ["Import.ConflictAdd"] = ("Добавить как новую запись", "Add as a new entry"),
        ["Import.ConflictSkip"] = ("Пропустить", "Skip"),
        ["Import.Apply"] = ("Импортировать ({0})", "Import ({0})"),
        ["Import.Done"] = ("Импорт завершён: добавлено {0}, обновлено {1}", "Import finished: {0} added, {1} updated"),
        ["Warn.AppBound"] = ("{0}: {1} паролей защищены App‑Bound Encryption (Chrome 127+) и недоступны другим программам. Экспортируйте их в браузере (Настройки → Менеджер паролей → Экспорт паролей) и импортируйте CSV‑файл.",
            "{0}: {1} passwords are protected by App-Bound Encryption (Chrome 127+) and cannot be read by other apps. Export them in the browser (Settings → Password Manager → Export passwords) and import the CSV file."),
        ["Warn.DecryptFailed"] = ("{0}: не удалось расшифровать записей: {1}.", "{0}: {1} entries could not be decrypted."),
        ["Warn.PrimaryPassword"] = ("{0}: основной пароль не указан или неверен — пароли этого профиля не импортированы.", "{0}: the primary password is missing or wrong — this profile was skipped."),
        ["Warn.YandexMaster"] = ("{0}: пароли защищены мастер‑паролем Яндекс Браузера. Отключите его в настройках паролей браузера или экспортируйте пароли в файл.",
            "{0}: passwords are protected by the Yandex Browser master password. Turn it off in the browser password settings or export the passwords to a file."),
        ["Warn.SkippedRows"] = ("Пропущено пустых строк: {0}", "Empty rows skipped: {0}"),
        ["Warn.Empty"] = ("{0}: нет данных для импорта", "{0}: nothing to import"),
        ["Warn.Error"] = ("{0}: {1}", "{0}: {1}"),

        // ---- export
        ["Export.Title"] = ("Экспорт паролей", "Export passwords"),
        ["Export.Subtitle"] = ("Будет экспортировано: {0} (кроме корзины). Выберите формат.", "{0} will be exported (trash excluded). Choose a format."),
        ["Export.Pkx"] = ("PassKeeper (.pkx)", "PassKeeper (.pkx)"),
        ["Export.PkxDesc"] = ("Зашифрованная копия — для резервного копирования и переноса", "Encrypted copy — for backups and moving between PCs"),
        ["Export.Kdbx"] = ("KeePass (.kdbx)", "KeePass (.kdbx)"),
        ["Export.KdbxDesc"] = ("Зашифрованная база KeePass 2, KeePassXC, KeePassDX", "Encrypted KeePass 2 / KeePassXC / KeePassDX database"),
        ["Export.CsvChrome"] = ("CSV для браузеров", "CSV for browsers"),
        ["Export.CsvChromeDesc"] = ("Chrome, Edge, Яндекс, Opera, Brave, Vivaldi", "Chrome, Edge, Yandex, Opera, Brave, Vivaldi"),
        ["Export.CsvFirefox"] = ("CSV для Firefox", "CSV for Firefox"),
        ["Export.CsvFirefoxDesc"] = ("Импорт паролей в Firefox и Thunderbird", "Import into Firefox and Thunderbird"),
        ["Export.JsonBitwarden"] = ("Bitwarden (JSON)", "Bitwarden (JSON)"),
        ["Export.JsonBitwardenDesc"] = ("Также Vaultwarden, Proton Pass, NordPass", "Also Vaultwarden, Proton Pass, NordPass"),
        ["Export.CsvBitwarden"] = ("Bitwarden (CSV)", "Bitwarden (CSV)"),
        ["Export.CsvBitwardenDesc"] = ("Универсальный CSV для большинства менеджеров", "Generic CSV understood by most managers"),
        ["Export.CsvOnePassword"] = ("1Password (CSV)", "1Password (CSV)"),
        ["Export.CsvOnePasswordDesc"] = ("Импорт в 1Password 8", "Import into 1Password 8"),
        ["Export.CsvLastPass"] = ("LastPass (CSV)", "LastPass (CSV)"),
        ["Export.CsvLastPassDesc"] = ("Также Dashlane, RoboForm, Keeper", "Also Dashlane, RoboForm, Keeper"),
        ["Export.CsvKeePassXc"] = ("KeePassXC (CSV)", "KeePassXC (CSV)"),
        ["Export.CsvKeePassXcDesc"] = ("Импорт CSV в KeePassXC", "KeePassXC CSV import"),
        ["Export.XmlKeePass"] = ("KeePass 2 (XML)", "KeePass 2 (XML)"),
        ["Export.XmlKeePassDesc"] = ("Незашифрованный XML KeePass 2", "Unencrypted KeePass 2 XML"),
        ["Export.CsvPassKeeper"] = ("CSV — все поля", "CSV — all fields"),
        ["Export.CsvPassKeeperDesc"] = ("Для Excel и собственных скриптов", "For Excel and your own scripts"),
        ["Export.JsonPassKeeper"] = ("JSON — все поля", "JSON — all fields"),
        ["Export.JsonPassKeeperDesc"] = ("Полная незашифрованная копия", "Complete unencrypted copy"),
        ["Export.Html"] = ("HTML для печати", "HTML for printing"),
        ["Export.HtmlDesc"] = ("Бумажная копия в сейф", "Paper copy for a safe"),
        ["Export.PlainWarning"] = ("Файл будет содержать пароли в открытом виде. Храните его в безопасном месте и удалите после использования.",
            "The file will contain passwords in plain text. Keep it safe and delete it after use."),
        ["Export.ConfirmMaster"] = ("Подтвердите мастер‑паролем", "Confirm with your master password"),
        ["Export.NeedMaster"] = ("Введите мастер‑пароль", "Enter the master password"),
        ["Export.Button"] = ("Экспортировать…", "Export…"),
        ["Export.PasswordTitle"] = ("Пароль для файла", "File password"),
        ["Export.PasswordText"] = ("Этим паролем будет зашифрован файл экспорта. Он понадобится при импорте.", "The export file is encrypted with this password. You will need it to import the file."),
        ["Export.Done"] = ("Экспортировано: {0}", "Exported: {0}"),

        // ---- tray / auto-type
        ["Tray.Open"] = ("Открыть PassKeeper", "Open PassKeeper"),
        ["Tray.Lock"] = ("Заблокировать", "Lock"),
        ["Tray.Generator"] = ("Генератор паролей", "Password generator"),
        ["Tray.Hotkey"] = ("Автоввод: {0}", "Auto-type: {0}"),
        ["Tray.Exit"] = ("Выход", "Exit"),
        ["Tray.Locked"] = ("заблокирован", "locked"),
        ["Tray.StillRunning"] = ("PassKeeper продолжает работать в фоне. Автоввод — {0}.", "PassKeeper keeps running in the background. Auto-type — {0}."),
        ["Tray.HotkeyFailed"] = ("Не удалось назначить горячую клавишу {0}: она занята другой программой. Выберите другую в настройках.",
            "Cannot register the {0} hotkey: it is used by another application. Choose another one in Settings."),
        ["AutoType.ErrorTitle"] = ("Автоввод", "Auto-type"),
        ["AutoType.Aborted"] = ("Автоввод прерван: активное окно изменилось.", "Auto-type stopped: the active window changed."),
        ["AutoType.Blocked"] = ("Windows не позволяет вводить текст в это окно (программа запущена от имени администратора).", "Windows blocks input into this window (the app runs as administrator)."),
        ["AutoType.Elevated"] = ("«{0}» запущено от имени администратора, и Windows не пропускает в него автоввод. {1} — в буфере обмена: вставьте сочетанием Ctrl+V.",
            "“{0}” runs as administrator, so Windows blocks auto-type into it. {1} is on the clipboard: paste it with Ctrl+V."),
        ["AutoType.ElevatedLogin"] = ("Логин: {0}", "Login: {0}"),
        ["AutoType.WhatPassword"] = ("Пароль", "The password"),
        ["AutoType.WhatPin"] = ("PIN‑код", "The PIN"),
        ["AutoType.WhatCode"] = ("Код", "The code"),
        ["AutoType.WhatKey"] = ("Ключ", "The key"),
        ["AutoType.NoForm"] = ("В окне клиента не найдены поля входа. Откройте окно входа и повторите.", "No login fields were found in the client window. Open its sign-in window and try again."),
        ["AutoType.WindowGone"] = ("Окно входа уже закрыто: откройте его снова — PassKeeper заполнит его по горячей клавише или автоматически.",
            "The sign-in window is closed: open it again and PassKeeper fills it with the hotkey or automatically."),
        ["AutoLogin.Paused"] = ("Автовход для «{0}» приостановлен: уже было {1} попытки за 10 минут. Проверьте пароль в записи.",
            "Automatic sign-in for “{0}” is paused: {1} attempts were made in 10 minutes. Check the password in the entry."),
        ["Details.More"] = ("Ещё", "More"),
        ["Details.AutoLoginOn"] = ("Включён: вход при появлении окна", "On: signs in when the window appears"),
        ["Details.AutoLoginChip"] = ("Автовход", "Auto sign-in"),
        ["ClientPicker.Title"] = ("Клиент или программа", "Client or program"),
        ["ClientPicker.Subtitle"] = ("Запущенные и установленные клиенты найдены автоматически. Можно выбрать и любое открытое окно.",
            "Running and installed clients are found automatically. Any open window can be chosen too."),
        ["ClientPicker.Searching"] = ("Поиск клиентов на компьютере…", "Looking for clients on this computer…"),
        ["ClientPicker.NoneFound"] = ("Известные клиенты на компьютере не найдены — выберите из каталога или открытое окно.", "No known clients were found on this computer: choose from the catalog or an open window."),
        ["ClientPicker.Running"] = ("Запущены сейчас", "Running now"),
        ["ClientPicker.RunningInfo"] = ("Процесс {0}", "Process {0}"),
        ["ClientPicker.RunningBadge"] = ("запущен", "running"),
        ["ClientPicker.Installed"] = ("Установлены", "Installed"),
        ["ClientPicker.InstalledInfo"] = ("Установлен на компьютере", "Installed on this computer"),
        ["ClientPicker.Windows"] = ("Другие открытые окна", "Other open windows"),
        ["ClientPicker.Catalog"] = ("Все поддерживаемые клиенты", "All supported clients"),
        ["EntryPicker.Title"] = ("Взять из записи", "Take from an entry"),
        ["EntryPicker.Subtitle"] = ("Логин, пароль и код 2FA будут скопированы в новую запись.", "The login, password and 2FA secret are copied into this entry."),
        ["Help.Title"] = ("Справка", "Help"),
        ["Help.Copied"] = ("Скопировано", "Copied"),
        ["AutoType.NoTarget"] = ("Не найдено окно для автоввода. Переключитесь в окно входа и нажмите горячую клавишу.", "No target window found. Switch to the login window and press the hotkey."),
    };
}
