namespace PassKeeper.Localization;

/// <summary>UI strings: key → (Russian, English).</summary>
internal static class Strings
{
    public static readonly Dictionary<string, (string Ru, string En)> Table = new()
    {
        // ---- common
        ["Common.Ok"] = ("ОК", "OK"),
        ["Common.Cancel"] = ("Отмена", "Cancel"),
        ["Common.Close"] = ("Закрыть", "Close"),
        ["Common.Continue"] = ("Продолжить", "Continue"),
        ["Common.Back"] = ("Назад", "Back"),
        ["Common.Save"] = ("Сохранить", "Save"),
        ["Common.Edit"] = ("Изменить", "Edit"),
        ["Common.Delete"] = ("Удалить", "Delete"),
        ["Common.Copy"] = ("Копировать", "Copy"),
        ["Common.Cut"] = ("Вырезать", "Cut"),
        ["Common.Paste"] = ("Вставить", "Paste"),
        ["Common.SelectAll"] = ("Выделить всё", "Select all"),
        ["Common.ShowHide"] = ("Показать / скрыть", "Show / hide"),
        ["Common.Password"] = ("Пароль", "Password"),
        ["Common.PasswordRepeat"] = ("Повторите пароль", "Repeat password"),
        ["Common.ErrorFormat"] = ("Ошибка: {0}", "Error: {0}"),
        ["Common.OfflineNote"] = ("Зашифровано и хранится только на этом компьютере", "Encrypted and stored only on this computer"),
        ["Plural.Entries"] = ("запись|записи|записей", "entry|entries"),

        // ---- setup
        ["Setup.Title"] = ("Добро пожаловать в PassKeeper", "Welcome to PassKeeper"),
        ["Setup.Subtitle"] = ("Создайте локальный профиль. Пароли хранятся только на этом компьютере и шифруются по современным стандартам (AES‑256‑GCM, Argon2id). Подключение к интернету не требуется.",
            "Create a local profile. Passwords stay on this computer and are encrypted with modern standards (AES‑256‑GCM, Argon2id). No internet connection is required."),
        ["Setup.UserName"] = ("Имя пользователя", "User name"),
        ["Setup.UserNamePlaceholder"] = ("Как к вам обращаться", "How should we call you"),
        ["Setup.Master"] = ("Мастер‑пароль", "Master password"),
        ["Setup.MasterPlaceholder"] = ("Не менее 8 символов", "At least 8 characters"),
        ["Setup.Confirm"] = ("Повторите мастер‑пароль", "Repeat master password"),
        ["Setup.ConfirmPlaceholder"] = ("Ещё раз", "Once again"),
        ["Setup.Autostart"] = ("Запускать PassKeeper при входе в Windows", "Start PassKeeper when I sign in to Windows"),
        ["Setup.Warning"] = ("Мастер‑пароль невозможно восстановить или сбросить. Запомните его — без него доступ к паролям будет потерян.",
            "The master password cannot be recovered or reset. Remember it — without it your passwords are lost."),
        ["Setup.Create"] = ("Создать профиль", "Create profile"),
        ["Setup.ErrName"] = ("Введите имя пользователя", "Enter a user name"),
        ["Setup.ErrShort"] = ("Пароль должен содержать не менее {0} символов", "The password must be at least {0} characters long"),
        ["Setup.ErrMismatch"] = ("Пароли не совпадают", "Passwords do not match"),

        // ---- PIN
        ["Pin.Title"] = ("Придумайте PIN‑код", "Choose a PIN"),
        ["Pin.Subtitle"] = ("PIN используется для быстрого входа при запуске и после {0} бездействия. После 5 неверных попыток потребуется мастер‑пароль.",
            "The PIN unlocks PassKeeper at start-up and after {0} of inactivity. After 5 wrong attempts the master password is required."),
        ["Pin.New"] = ("PIN‑код", "PIN"),
        ["Pin.Repeat"] = ("Повторите PIN‑код", "Repeat PIN"),
        ["Pin.Hint"] = ("От 4 до 12 цифр. Рекомендуем 6 и более.", "4 to 12 digits. 6 or more recommended."),
        ["Pin.Save"] = ("Сохранить PIN", "Save PIN"),
        ["Pin.ErrLength"] = ("PIN должен состоять из {0}–{1} цифр", "The PIN must have {0}–{1} digits"),
        ["Pin.ErrMismatch"] = ("PIN‑коды не совпадают", "PINs do not match"),
        ["Pin.ErrSimple"] = ("Слишком простой PIN (одинаковые цифры или последовательность)", "PIN is too simple (repeated digits or a sequence)"),
        ["Pin.Changed"] = ("PIN‑код изменён", "PIN changed"),

        // ---- unlock
        ["Unlock.Greeting"] = ("Здравствуйте, {0}!", "Hello, {0}!"),
        ["Unlock.PromptPin"] = ("Введите PIN‑код, чтобы разблокировать хранилище", "Enter your PIN to unlock the vault"),
        ["Unlock.PromptMaster"] = ("Введите мастер‑пароль, чтобы разблокировать хранилище", "Enter your master password to unlock the vault"),
        ["Unlock.PinPlaceholder"] = ("PIN‑код", "PIN"),
        ["Unlock.MasterPlaceholder"] = ("Мастер‑пароль", "Master password"),
        ["Unlock.Button"] = ("Разблокировать", "Unlock"),
        ["Unlock.UseMaster"] = ("Войти с мастер‑паролем", "Use master password"),
        ["Unlock.UsePin"] = ("Войти с PIN‑кодом", "Use PIN"),
        ["Unlock.WrongPin"] = ("Неверный PIN‑код. Осталось попыток: {0}", "Wrong PIN. Attempts left: {0}"),
        ["Unlock.WrongMaster"] = ("Неверный мастер‑пароль", "Wrong master password"),
        ["Unlock.LockedOut"] = ("Слишком много неверных попыток. PIN‑код сброшен — войдите с мастер‑паролем и задайте новый PIN.",
            "Too many wrong attempts. The PIN was reset — sign in with the master password and set a new PIN."),
        ["Unlock.PinReset"] = ("PIN‑код недоступен. Войдите с мастер‑паролем.", "The PIN is not available. Sign in with the master password."),
        ["Unlock.Corrupted"] = ("Не удалось открыть хранилище: {0}", "Cannot open the vault: {0}"),

        // ---- quick unlock / picker / suggestions
        ["Quick.Title"] = ("Разблокируйте для автозаполнения", "Unlock to autofill"),
        ["Quick.TitleFor"] = ("Разблокируйте для автоввода: {0}", "Unlock to auto-type into {0}"),
        ["Picker.Target"] = ("Автоввод: {0}", "Auto-type: {0}"),
        ["Picker.Search"] = ("Поиск записи", "Search entries"),
        ["Picker.Hint"] = ("Enter — ввести · ↑↓ — выбор · Esc — отмена", "Enter — type · ↑↓ — select · Esc — cancel"),
        ["Suggest.For"] = ("Для: {0}", "For: {0}"),
        ["Suggest.Footer"] = ("{0} — автоввод в активное окно", "{0} — auto-type into the active window"),
        ["Suggest.PasswordOnly"] = ("только пароль", "password only"),
        ["Suggest.FillOtp"] = ("вставить код 2FA", "fill 2FA code"),
        ["Suggest.FillPin"] = ("вставить PIN‑код", "fill PIN"),
        ["Suggest.FillKey"] = ("вставить ключ / токен", "fill key / token"),
        ["Suggest.Unlock"] = ("PassKeeper заблокирован", "PassKeeper is locked"),
        ["Suggest.UnlockHint"] = ("Нажмите, чтобы разблокировать и заполнить", "Click to unlock and fill"),

        // ---- vault
        ["Nav.All"] = ("Все записи", "All entries"),
        ["Nav.Favorites"] = ("Избранное", "Favorites"),
        ["Nav.Folders"] = ("Папки", "Folders"),
        ["Nav.Trash"] = ("Корзина", "Trash"),
        ["Vault.Generator"] = ("Генератор паролей", "Password generator"),
        ["Vault.Import"] = ("Импорт", "Import"),
        ["Vault.Export"] = ("Экспорт", "Export"),
        ["Vault.Settings"] = ("Настройки", "Settings"),
        ["Vault.LocalProfile"] = ("Локальный профиль", "Local profile"),
        ["Vault.LockTip"] = ("Заблокировать (Ctrl+L)", "Lock (Ctrl+L)"),
        ["Vault.SearchPlaceholder"] = ("Поиск (Ctrl+F)", "Search (Ctrl+F)"),
        ["Vault.AddTip"] = ("Новая запись (Ctrl+N)", "New entry (Ctrl+N)"),
        ["Vault.AddShort"] = ("Добавить", "Add"),
        ["Vault.CopyLogin"] = ("Копировать логин", "Copy login"),
        ["Vault.CopyPassword"] = ("Копировать пароль", "Copy password"),
        ["Vault.OpenSite"] = ("Открыть сайт", "Open website"),
        ["Vault.Favorite"] = ("В избранное", "Add to favorites"),
        ["Vault.Unfavorite"] = ("Убрать из избранного", "Remove from favorites"),
        ["Vault.Duplicate"] = ("Дублировать", "Duplicate"),
        ["Vault.CopyOf"] = ("{0} (копия)", "{0} (copy)"),
        ["Vault.Restore"] = ("Восстановить", "Restore"),
        ["Vault.Restored"] = ("Запись восстановлена", "Entry restored"),
        ["Vault.MovedToTrash"] = ("Запись перемещена в корзину", "Entry moved to trash"),
        ["Vault.DeleteForever"] = ("Удалить навсегда", "Delete forever"),
        ["Vault.DeleteForeverTitle"] = ("Удалить запись навсегда?", "Delete the entry forever?"),
        ["Vault.DeleteForeverText"] = ("Запись «{0}» будет удалена без возможности восстановления.", "“{0}” will be deleted permanently."),
        ["Vault.DeletedForever"] = ("Запись удалена", "Entry deleted"),
        ["Vault.EmptyTrash"] = ("Очистить корзину", "Empty trash"),
        ["Vault.EmptyTrashTitle"] = ("Очистить корзину?", "Empty the trash?"),
        ["Vault.EmptyTrashText"] = ("Все записи в корзине будут удалены без возможности восстановления.", "All entries in the trash will be deleted permanently."),
        ["Vault.TrashEmptied"] = ("Корзина очищена ({0})", "Trash emptied ({0})"),
        ["Vault.NoEntries"] = ("Здесь пока пусто", "Nothing here yet"),
        ["Vault.NoEntriesHint"] = ("Добавьте первую запись или импортируйте пароли из браузера и других менеджеров.", "Add your first entry or import passwords from your browser and other managers."),
        ["Vault.EmptyFolder"] = ("Нет записей", "No entries"),
        ["Vault.NothingFound"] = ("Ничего не найдено", "Nothing found"),
        ["Vault.NothingFoundHint"] = ("Попробуйте изменить запрос", "Try a different search"),
        ["Vault.TrashEmpty"] = ("Корзина пуста", "Trash is empty"),
        ["Vault.TrashEmptyHint"] = ("Удалённые записи хранятся здесь, пока вы не очистите корзину.", "Deleted entries stay here until you empty the trash."),
        ["Sort.Name"] = ("По названию", "By name"),
        ["Sort.Modified"] = ("По изменению", "Recently changed"),
        ["Sort.Used"] = ("По использованию", "Recently used"),

        // ---- details
        ["Details.EmptyTitle"] = ("Выберите запись", "Select an entry"),
        ["Details.EmptyHint"] = ("или создайте новую — Ctrl+N", "or create a new one — Ctrl+N"),
        ["Details.StatTotal"] = ("паролей", "passwords"),
        ["Details.StatWeak"] = ("слабых", "weak"),
        ["Details.StatReused"] = ("повторяются", "reused"),
        ["Details.AutoTypeTip"] = ("Автозаполнение: откройте окно входа на сайте или в программе и нажмите {0} — PassKeeper сам подставит логин и пароль. При фокусе на поле входа также появится подсказка.",
            "Autofill: open a sign-in page or app window and press {0} — PassKeeper types the login and password for you. A suggestion also appears when a login field is focused."),
        ["Details.CustomFields"] = ("Дополнительные поля", "Custom fields"),
        ["Details.AutoType"] = ("Автоввод", "Auto-type"),
        ["Details.AutoTypeButton"] = ("Автоввод", "Auto-type"),
        ["Details.AutoTypeButtonTip"] = ("Свернуть PassKeeper и ввести логин и пароль в предыдущее окно", "Minimize PassKeeper and type the login and password into the previous window"),
        ["Details.History"] = ("История паролей ({0})", "Password history ({0})"),
        ["Details.Meta"] = ("Создано {0} · Изменено {1}", "Created {0} · Modified {1}"),
        ["Details.Used"] = ("Использовано {0}", "Used {0}"),
        ["Details.InTrash"] = ("В корзине", "In trash"),
        ["Details.Open"] = ("Открыть", "Open"),
        ["Details.Sec"] = ("с", "s"),

        // ---- fields
        ["Field.Title"] = ("Название", "Title"),
        ["Field.Login"] = ("Логин", "Login"),
        ["Field.Password"] = ("Пароль", "Password"),
        ["Field.Website"] = ("Сайт", "Website"),
        ["Field.Email"] = ("Эл. почта", "Email"),
        ["Field.Phone"] = ("Телефон", "Phone"),
        ["Field.Key"] = ("Ключ / токен", "Key / token"),
        ["Field.Totp"] = ("Код 2FA (TOTP)", "2FA code (TOTP)"),
        ["Field.Folder"] = ("Папка", "Folder"),
        ["Field.Notes"] = ("Заметки", "Notes"),
        ["Field.Windows"] = ("Окна приложений", "Application windows"),
        ["Field.ExtraUrls"] = ("Дополнительные адреса", "Additional URLs"),
        ["Field.Sequence"] = ("Последовательность автоввода", "Auto-type sequence"),

        // ---- editor
        ["Editor.NewTitle"] = ("Новая запись", "New entry"),
        ["Editor.EditTitle"] = ("Редактирование", "Edit entry"),
        ["Editor.TitlePlaceholder"] = ("Например, Почта или 1С", "e.g. Mail or CRM"),
        ["Editor.LoginPlaceholder"] = ("Логин, e‑mail или телефон", "Login, e-mail or phone"),
        ["Editor.KeyPlaceholder"] = ("API‑ключ, лицензия, токен", "API key, licence, token"),
        ["Editor.TotpPlaceholder"] = ("otpauth://… или секрет Base32", "otpauth://… or Base32 secret"),
        ["Editor.FolderPlaceholder"] = ("Без папки (вложенность через /)", "No folder (use / for sub-folders)"),
        ["Editor.Generate"] = ("Сгенерировать пароль", "Generate password"),
        ["Editor.Favorite"] = ("Добавить в избранное", "Add to favorites"),
        ["Editor.AddField"] = ("+ Добавить поле", "+ Add field"),
        ["Editor.NoFields"] = ("Например: ПИН карты, кодовое слово, номер договора.", "e.g. card PIN, secret word, contract number."),
        ["Editor.FieldName"] = ("Название поля", "Field name"),
        ["Editor.FieldValue"] = ("Значение", "Value"),
        ["Editor.FieldProtected"] = ("Скрывать значение", "Hide the value"),
        ["Editor.FieldDefault"] = ("Поле", "Field"),
        ["Editor.AutoTypeSection"] = ("Автоввод в приложениях", "Auto-type for applications"),
        ["Editor.AutoTypeHelp"] = ("Для сайтов достаточно адреса. Для программ (VPN, 1С, RDP, VDI) выберите клиент из списка или укажите часть заголовка окна или имя процесса — по одному на строку, можно использовать *.",
            "For websites the URL is enough. For desktop apps (VPN, RDP, VDI) pick a client from the list or enter part of the window title or the process name — one per line, * wildcards allowed."),
        ["Editor.PhonePlaceholder"] = ("+7 900 000-00-00", "+1 555 000 0000"),
        ["Editor.AddApp"] = ("Клиент из списка", "Pick a client"),
        ["Editor.AppAdded"] = ("Добавлено: {0}", "Added: {0}"),
        ["Editor.PinHint"] = ("PIN токена или смарт-карты берётся из дополнительного поля «PIN», а если его нет — из пароля.",
            "A token or smart-card PIN is taken from a custom field named “PIN”, otherwise from the password."),
        ["Editor.WindowsPlaceholder"] = ("*1С:Предприятие*\nmstsc.exe", "*Remote Desktop*\nputty.exe"),
        ["Editor.ExtraUrlsPlaceholder"] = ("Другие адреса этого же аккаунта, по одному на строку", "Other addresses of the same account, one per line"),
        ["Editor.SequenceHelp"] = ("Пусто — заполнение по полям окна. Доступно: {USERNAME} {PASSWORD} {PIN} {EMAIL} {PHONE} {KEY} {TOTP} {TAB} {ENTER} {DELAY 500} {S:Поле}",
            "Empty — fill the window's fields. Available: {USERNAME} {PASSWORD} {PIN} {EMAIL} {PHONE} {KEY} {TOTP} {TAB} {ENTER} {DELAY 500} {S:Field}"),
        ["Editor.ErrTitle"] = ("Укажите название записи", "Enter a title"),
        ["Editor.ErrSequence"] = ("Ошибка в последовательности автоввода: {0}", "Auto-type sequence error: {0}"),
        ["Editor.ErrTotp"] = ("Неверный формат 2FA: нужен секрет Base32 или ссылка otpauth://", "Invalid 2FA value: use a Base32 secret or an otpauth:// link"),
        ["Editor.Created"] = ("Запись создана", "Entry created"),
        ["Editor.Saved"] = ("Изменения сохранены", "Changes saved"),
        ["Editor.DiscardTitle"] = ("Отменить изменения?", "Discard changes?"),
        ["Editor.DiscardText"] = ("Несохранённые изменения будут потеряны.", "Unsaved changes will be lost."),
        ["Editor.Discard"] = ("Не сохранять", "Discard"),

        // ---- generator & strength
        ["Generator.Title"] = ("Генератор паролей", "Password generator"),
        ["Generator.Length"] = ("Длина", "Length"),
        ["Generator.ExcludeAmbiguous"] = ("Исключить похожие символы (I, l, 1, O, 0)", "Exclude look-alike characters (I, l, 1, O, 0)"),
        ["Generator.Regenerate"] = ("Сгенерировать заново", "Regenerate"),
        ["Generator.Use"] = ("Использовать", "Use password"),
        ["Generator.CopyAndClose"] = ("Копировать и закрыть", "Copy and close"),
        ["Strength.Empty"] = ("Надёжность пароля", "Password strength"),
        ["Strength.Format"] = ("{0} · ≈{1} бит", "{0} · ≈{1} bits"),
        ["Strength.0"] = ("Очень слабый", "Very weak"),
        ["Strength.1"] = ("Слабый", "Weak"),
        ["Strength.2"] = ("Средний", "Fair"),
        ["Strength.3"] = ("Надёжный", "Strong"),
        ["Strength.4"] = ("Очень надёжный", "Very strong"),

        // ---- toasts
        ["Toast.PasswordCopied"] = ("Пароль скопирован", "Password copied"),
        ["Toast.LoginCopied"] = ("Логин скопирован", "Login copied"),
        ["Toast.TotpCopied"] = ("Код 2FA скопирован", "2FA code copied"),
        ["Toast.Copied"] = ("{0}: скопировано", "{0} copied"),
        ["Toast.CopiedSecret"] = ("{0}: скопировано", "{0} copied"),
        ["Toast.WillClear"] = ("очистится через {0} с", "clears in {0} s"),
        ["Toast.ClipboardBusy"] = ("Буфер обмена занят другой программой", "The clipboard is busy"),

        // ---- settings
        ["Settings.Title"] = ("Настройки", "Settings"),
        ["Settings.General"] = ("Общие", "General"),
        ["Settings.Language"] = ("Язык интерфейса", "Language"),
        ["Settings.Theme"] = ("Оформление", "Appearance"),
        ["Settings.ThemeDark"] = ("Тёмное", "Dark"),
        ["Settings.ThemeLight"] = ("Светлое", "Light"),
        ["Settings.ThemeSystem"] = ("Как в Windows", "System"),
        ["Settings.Autostart"] = ("Запускать вместе с Windows", "Start with Windows"),
        ["Settings.AutostartHint"] = ("Работает без прав администратора; PassKeeper запускается свёрнутым в трей", "No administrator rights needed; PassKeeper starts minimized to the tray"),
        ["Settings.AutostartMachine"] = ("Автозапуск включён администратором для всех пользователей", "Autostart is enabled by the administrator for all users"),
        ["Settings.Tray"] = ("Сворачивать в трей при закрытии", "Minimize to tray on close"),
        ["Settings.TrayHint"] = ("Автозаполнение и горячие клавиши работают, пока PassKeeper запущен", "Autofill and hotkeys work while PassKeeper is running"),
        ["Settings.Security"] = ("Безопасность", "Security"),
        ["Settings.AutoLock"] = ("Автоблокировка при бездействии", "Auto-lock after inactivity"),
        ["Settings.AutoLockHint"] = ("Если за это время не было действий с клавиатурой и мышью, потребуется PIN‑код. Точность — до секунды, рекомендуется 8 ч.",
            "With no keyboard or mouse activity for this long, the PIN is required. Set to the second; 8 h is recommended."),
        ["Duration.Hours"] = ("часы", "hours"),
        ["Duration.Minutes"] = ("минуты", "minutes"),
        ["Duration.Seconds"] = ("секунды", "seconds"),
        ["Duration.Minimum"] = ("Минимум — {0}: будет применено это значение", "The minimum is {0}: this value will be used"),
        ["Settings.Clipboard"] = ("Очищать буфер обмена", "Clear clipboard"),
        ["Settings.ClipboardHint"] = ("Скопированные пароли не попадают в журнал буфера Windows", "Copied passwords are excluded from Windows clipboard history"),
        ["Settings.LockOnWindowsLock"] = ("Блокировать при блокировке Windows (Win+L)", "Lock when Windows is locked (Win+L)"),
        ["Settings.ChangeMaster"] = ("Сменить мастер‑пароль", "Change master password"),
        ["Settings.ChangePin"] = ("Сменить PIN‑код", "Change PIN"),
        ["Settings.Autofill"] = ("Автозаполнение", "Autofill"),
        ["Settings.Hotkey"] = ("Горячая клавиша автоввода", "Auto-type hotkey"),
        ["Settings.HotkeyHint"] = ("Работает во всех браузерах и программах", "Works in every browser and application"),
        ["Settings.HotkeyPress"] = ("Нажмите сочетание…", "Press a shortcut…"),
        ["Settings.HotkeyTaken"] = ("Сочетание занято другой программой", "The shortcut is used by another application"),
        ["Settings.Suggestions"] = ("Подсказки у полей входа", "Suggestions at login fields"),
        ["Settings.SuggestionsHint"] = ("При фокусе на поле логина или пароля в браузере или программе PassKeeper предложит подходящую запись",
            "When a login or password field is focused in a browser or app, PassKeeper offers the matching entry"),
        ["Settings.Submit"] = ("Нажимать Enter после заполнения", "Press Enter after filling"),
        ["Settings.Compatible"] = ("Совместимый режим ввода", "Compatibility typing mode"),
        ["Settings.CompatibleHint"] = ("Для RDP, терминалов и старых программ, которые не принимают Unicode‑ввод", "For RDP, terminals and legacy apps that ignore Unicode input"),
        ["Settings.KeyDelay"] = ("Задержка между нажатиями", "Delay between keystrokes"),
        ["Settings.Data"] = ("Данные", "Data"),
        ["Settings.DataFolder"] = ("Папка хранилища", "Vault folder"),
        ["Settings.OpenFolder"] = ("Открыть папку", "Open folder"),
        ["Settings.Backup"] = ("Сохранить резервную копию…", "Save a backup…"),
        ["Settings.BackupFilter"] = ("Хранилище PassKeeper", "PassKeeper vault"),
        ["Settings.BackupDone"] = ("Резервная копия сохранена", "Backup saved"),
        ["Settings.About"] = ("О программе", "About"),
        ["Settings.AboutText"] = ("Менеджер паролей для изолированных сетей: не использует интернет, телеметрию и облака. Шифрование AES‑256‑GCM, ключ из мастер‑пароля — Argon2id (64 МБ, 3 прохода).",
            "Password manager for isolated networks: no internet, telemetry or cloud. AES‑256‑GCM encryption, key derived from the master password with Argon2id (64 MB, 3 passes)."),
        ["Settings.ModeUser"] = ("Установлено для текущего пользователя", "Installed for the current user"),
        ["Settings.ModeMachine"] = ("Установлено для всех пользователей", "Installed for all users"),
        ["Settings.ModePortable"] = ("Портативный режим", "Portable mode"),
        ["Settings.Uninstall"] = ("Удалить PassKeeper…", "Uninstall PassKeeper…"),
        ["Settings.ModeStandalone"] = ("Запущено без установки", "Running without installation"),
        ["Settings.Minutes"] = ("{0} мин", "{0} min"),
        ["Settings.Hours"] = ("{0} ч", "{0} h"),
        ["Settings.Seconds"] = ("{0} с", "{0} s"),
        ["Settings.Milliseconds"] = ("{0} мс", "{0} ms"),
        ["Settings.Never"] = ("Никогда", "Never"),
        ["Settings.Recommended"] = ("(рекомендуется)", "(recommended)"),
        ["ChangeMaster.Title"] = ("Смена мастер‑пароля", "Change master password"),
        ["ChangeMaster.Text"] = ("Хранилище будет перешифровано новым ключом. PIN‑код продолжит работать.", "The vault key will be re-wrapped with the new password. Your PIN keeps working."),
        ["ChangeMaster.Current"] = ("Текущий мастер‑пароль", "Current master password"),
        ["ChangeMaster.New"] = ("Новый мастер‑пароль", "New master password"),
        ["ChangeMaster.Confirm"] = ("Повторите новый мастер‑пароль", "Repeat new master password"),
        ["ChangeMaster.Button"] = ("Сменить пароль", "Change password"),
        ["ChangeMaster.Done"] = ("Мастер‑пароль изменён", "Master password changed"),

        // ---- import
        ["Import.Title"] = ("Импорт паролей", "Import passwords"),
        ["Import.Subtitle"] = ("Перенесите пароли из браузеров, других менеджеров паролей и файлов. Дубликаты будут найдены автоматически.",
            "Bring in passwords from browsers, other password managers and files. Duplicates are detected automatically."),
        ["Import.Browsers"] = ("Браузеры на этом компьютере", "Browsers on this computer"),
        ["Import.Refresh"] = ("Обновить", "Refresh"),
        ["Import.NoBrowsers"] = ("Браузеры с сохранёнными паролями не найдены.", "No browsers with saved passwords were found."),
        ["Import.FromBrowsers"] = ("Импортировать из выбранных", "Import from selected"),
        ["Import.FromFileTitle"] = ("Файл экспорта", "Export file"),
        ["Import.Formats"] = ("CSV любых браузеров (Chrome, Edge, Яндекс, Opera, Firefox, Safari), KeePass / KeePassXC (KDBX, XML, CSV), Bitwarden (JSON, CSV), 1Password (1PUX, CSV), LastPass, Dashlane, NordPass, Proton Pass, RoboForm, Keeper, Kaspersky Password Manager (TXT), PassKeeper (PKX, JSON). Формат определяется автоматически.",
            "CSV from any browser (Chrome, Edge, Yandex, Opera, Firefox, Safari), KeePass / KeePassXC (KDBX, XML, CSV), Bitwarden (JSON, CSV), 1Password (1PUX, CSV), LastPass, Dashlane, NordPass, Proton Pass, RoboForm, Keeper, Kaspersky Password Manager (TXT), PassKeeper (PKX, JSON). The format is detected automatically."),
        ["Import.ChooseFile"] = ("Выбрать файл…", "Choose file…"),
        ["Import.ChromeTip"] = ("Chrome 127+ шифрует новые пароли так, что другие программы не могут их прочитать. Если часть паролей не импортировалась, экспортируйте их в браузере (Настройки → Менеджер паролей → Экспорт) и выберите полученный CSV.",
            "Chrome 127+ encrypts new passwords so that other apps cannot read them. If some passwords were skipped, export them in the browser (Settings → Password Manager → Export) and choose the CSV file."),
        ["Import.Other"] = ("Другие источники", "Other sources"),
        ["Import.WindowsCredentials"] = ("Диспетчер учётных данных Windows", "Windows Credential Manager"),
        ["Import.WindowsCredentialsHint"] = ("Общие учётные данные текущего пользователя", "Generic credentials of the current user"),
        ["Import.Read"] = ("Прочитать", "Read"),
        ["Import.Reading"] = ("Чтение и расшифровка данных…", "Reading and decrypting…"),
        ["Import.Supported"] = ("Поддерживаемые файлы", "Supported files"),
        ["Import.AllFiles"] = ("Все файлы", "All files"),
        ["Import.KdbxPasswordTitle"] = ("База KeePass", "KeePass database"),
        ["Import.PkxPasswordTitle"] = ("Резервная копия PassKeeper", "PassKeeper backup"),
        ["Import.FilePasswordText"] = ("Файл «{0}» зашифрован. Введите пароль.", "“{0}” is encrypted. Enter its password."),
        ["Import.KeyFile"] = ("Файл‑ключ…", "Key file…"),
        ["Import.NoKeyFile"] = ("Файл‑ключ не выбран (необязательно)", "No key file (optional)"),
        ["Import.WrongPassword"] = ("Неверный пароль или файл‑ключ.", "Wrong password or key file."),
        ["Import.ErrorTitle"] = ("Не удалось импортировать", "Import failed"),
        ["Import.ErrorText"] = ("Не удалось прочитать файл: {0}", "Cannot read the file: {0}"),
        ["Import.FirefoxPrimaryTitle"] = ("Основной пароль Firefox", "Firefox primary password"),
        ["Import.FirefoxPrimaryText"] = ("В профиле «{0}» установлен основной пароль. Введите его, чтобы расшифровать сохранённые пароли.", "Profile “{0}” is protected by a primary password. Enter it to decrypt the saved logins."),
        ["Import.Found"] = ("Найдено: {0}", "Found: {0}"),
        ["Import.CountNew"] = ("Новых: {0}", "New: {0}"),
        ["Import.CountConflict"] = ("Другой пароль: {0}", "Different password: {0}"),
        ["Import.CountDuplicate"] = ("Уже есть: {0}", "Already saved: {0}"),
        ["Import.StatusNew"] = ("Новая", "New"),
        ["Import.StatusConflict"] = ("Другой пароль", "Changed"),
        ["Import.StatusDuplicate"] = ("Уже есть", "Exists"),
        ["Import.SelectAll"] = ("Выбрать все", "Select all"),
        ["Import.Filter"] = ("Фильтр", "Filter"),
        ["Import.TargetFolder"] = ("Поместить в папку", "Put into folder"),
        ["Import.NoFolder"] = ("Сохранить исходные папки", "Keep original folders"),
        ["Import.Conflicts"] = ("Если пароль отличается", "If the password differs"),
        ["Import.ConflictUpdate"] = ("Обновить пароль (старый — в историю)", "Update password (keep old in history)"),
        ["Import.ConflictAdd"] = ("Добавить как новую запись", "Add as a new entry"),
        ["Import.ConflictSkip"] = ("Пропустить", "Skip"),
        ["Import.Apply"] = ("Импортировать ({0})", "Import ({0})"),
        ["Import.Done"] = ("Импорт завершён: добавлено {0}, обновлено {1}", "Import finished: {0} added, {1} updated"),
        ["Warn.AppBound"] = ("{0}: {1} паролей защищены App‑Bound Encryption (Chrome 127+) и недоступны другим программам. Экспортируйте их в браузере (Настройки → Менеджер паролей → Экспорт паролей) и импортируйте CSV‑файл.",
            "{0}: {1} passwords are protected by App-Bound Encryption (Chrome 127+) and cannot be read by other apps. Export them in the browser (Settings → Password Manager → Export passwords) and import the CSV file."),
        ["Warn.DecryptFailed"] = ("{0}: не удалось расшифровать записей: {1}.", "{0}: {1} entries could not be decrypted."),
        ["Warn.PrimaryPassword"] = ("{0}: основной пароль не указан или неверен — пароли этого профиля не импортированы.", "{0}: the primary password is missing or wrong — this profile was skipped."),
        ["Warn.YandexMaster"] = ("{0}: пароли защищены мастер‑паролем Яндекс Браузера. Отключите его в настройках паролей браузера или экспортируйте пароли в файл.",
            "{0}: passwords are protected by the Yandex Browser master password. Turn it off in the browser password settings or export the passwords to a file."),
        ["Warn.SkippedRows"] = ("Пропущено пустых строк: {0}", "Empty rows skipped: {0}"),
        ["Warn.Empty"] = ("{0}: нет данных для импорта", "{0}: nothing to import"),
        ["Warn.Error"] = ("{0}: {1}", "{0}: {1}"),

        // ---- export
        ["Export.Title"] = ("Экспорт паролей", "Export passwords"),
        ["Export.Subtitle"] = ("Будет экспортировано: {0} (кроме корзины). Выберите формат.", "{0} will be exported (trash excluded). Choose a format."),
        ["Export.Pkx"] = ("PassKeeper (.pkx)", "PassKeeper (.pkx)"),
        ["Export.PkxDesc"] = ("Зашифрованная копия — для резервного копирования и переноса", "Encrypted copy — for backups and moving between PCs"),
        ["Export.Kdbx"] = ("KeePass (.kdbx)", "KeePass (.kdbx)"),
        ["Export.KdbxDesc"] = ("Зашифрованная база KeePass 2, KeePassXC, KeePassDX", "Encrypted KeePass 2 / KeePassXC / KeePassDX database"),
        ["Export.CsvChrome"] = ("CSV для браузеров", "CSV for browsers"),
        ["Export.CsvChromeDesc"] = ("Chrome, Edge, Яндекс, Opera, Brave, Vivaldi", "Chrome, Edge, Yandex, Opera, Brave, Vivaldi"),
        ["Export.CsvFirefox"] = ("CSV для Firefox", "CSV for Firefox"),
        ["Export.CsvFirefoxDesc"] = ("Импорт паролей в Firefox и Thunderbird", "Import into Firefox and Thunderbird"),
        ["Export.JsonBitwarden"] = ("Bitwarden (JSON)", "Bitwarden (JSON)"),
        ["Export.JsonBitwardenDesc"] = ("Также Vaultwarden, Proton Pass, NordPass", "Also Vaultwarden, Proton Pass, NordPass"),
        ["Export.CsvBitwarden"] = ("Bitwarden (CSV)", "Bitwarden (CSV)"),
        ["Export.CsvBitwardenDesc"] = ("Универсальный CSV для большинства менеджеров", "Generic CSV understood by most managers"),
        ["Export.CsvOnePassword"] = ("1Password (CSV)", "1Password (CSV)"),
        ["Export.CsvOnePasswordDesc"] = ("Импорт в 1Password 8", "Import into 1Password 8"),
        ["Export.CsvLastPass"] = ("LastPass (CSV)", "LastPass (CSV)"),
        ["Export.CsvLastPassDesc"] = ("Также Dashlane, RoboForm, Keeper", "Also Dashlane, RoboForm, Keeper"),
        ["Export.CsvKeePassXc"] = ("KeePassXC (CSV)", "KeePassXC (CSV)"),
        ["Export.CsvKeePassXcDesc"] = ("Импорт CSV в KeePassXC", "KeePassXC CSV import"),
        ["Export.XmlKeePass"] = ("KeePass 2 (XML)", "KeePass 2 (XML)"),
        ["Export.XmlKeePassDesc"] = ("Незашифрованный XML KeePass 2", "Unencrypted KeePass 2 XML"),
        ["Export.CsvPassKeeper"] = ("CSV — все поля", "CSV — all fields"),
        ["Export.CsvPassKeeperDesc"] = ("Для Excel и собственных скриптов", "For Excel and your own scripts"),
        ["Export.JsonPassKeeper"] = ("JSON — все поля", "JSON — all fields"),
        ["Export.JsonPassKeeperDesc"] = ("Полная незашифрованная копия", "Complete unencrypted copy"),
        ["Export.Html"] = ("HTML для печати", "HTML for printing"),
        ["Export.HtmlDesc"] = ("Бумажная копия в сейф", "Paper copy for a safe"),
        ["Export.PlainWarning"] = ("Файл будет содержать пароли в открытом виде. Храните его в безопасном месте и удалите после использования.",
            "The file will contain passwords in plain text. Keep it safe and delete it after use."),
        ["Export.ConfirmMaster"] = ("Подтвердите мастер‑паролем", "Confirm with your master password"),
        ["Export.NeedMaster"] = ("Введите мастер‑пароль", "Enter the master password"),
        ["Export.Button"] = ("Экспортировать…", "Export…"),
        ["Export.PasswordTitle"] = ("Пароль для файла", "File password"),
        ["Export.PasswordText"] = ("Этим паролем будет зашифрован файл экспорта. Он понадобится при импорте.", "The export file is encrypted with this password. You will need it to import the file."),
        ["Export.Done"] = ("Экспортировано: {0}", "Exported: {0}"),

        // ---- tray / auto-type
        ["Tray.Open"] = ("Открыть PassKeeper", "Open PassKeeper"),
        ["Tray.Lock"] = ("Заблокировать", "Lock"),
        ["Tray.Generator"] = ("Генератор паролей", "Password generator"),
        ["Tray.Hotkey"] = ("Автоввод: {0}", "Auto-type: {0}"),
        ["Tray.Exit"] = ("Выход", "Exit"),
        ["Tray.Locked"] = ("заблокирован", "locked"),
        ["Tray.StillRunning"] = ("PassKeeper продолжает работать в фоне. Автоввод — {0}.", "PassKeeper keeps running in the background. Auto-type — {0}."),
        ["Tray.HotkeyFailed"] = ("Не удалось назначить горячую клавишу {0}: она занята другой программой. Выберите другую в настройках.",
            "Cannot register the {0} hotkey: it is used by another application. Choose another one in Settings."),
        ["AutoType.ErrorTitle"] = ("Автоввод", "Auto-type"),
        ["AutoType.Aborted"] = ("Автоввод прерван: активное окно изменилось.", "Auto-type stopped: the active window changed."),
        ["AutoType.Blocked"] = ("Windows не позволяет вводить текст в это окно (программа запущена от имени администратора).", "Windows blocks input into this window (the app runs as administrator)."),
        ["AutoType.Elevated"] = ("«{0}» запущено от имени администратора, и Windows не пропускает в него автоввод. {1} — в буфере обмена: вставьте сочетанием Ctrl+V.",
            "“{0}” runs as administrator, so Windows blocks auto-type into it. {1} is on the clipboard: paste it with Ctrl+V."),
        ["AutoType.ElevatedLogin"] = ("Логин: {0}", "Login: {0}"),
        ["AutoType.WhatPassword"] = ("Пароль", "The password"),
        ["AutoType.WhatPin"] = ("PIN‑код", "The PIN"),
        ["AutoType.WhatCode"] = ("Код", "The code"),
        ["AutoType.WhatKey"] = ("Ключ", "The key"),
        ["AutoType.NoTarget"] = ("Не найдено окно для автоввода. Переключитесь в окно входа и нажмите горячую клавишу.", "No target window found. Switch to the login window and press the hotkey."),
    };
}
